LTO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_LOCK_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

LEADER_ENABLE  = no
COMBO_ENABLE  = no
UNICODEMAP_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no